var ddoe = {
    1: { fileName: 'spiky.jpg', desc: 'Eagel Update, Day 1:<br/>Enjoying the day with his spiky friends!' },
    2: { fileName: 'lockers.jpeg', desc: 'Eagel Update, Day 2:<br/>Wait, why does it smell like cheese here (if you don\'t get the context, you\'re lucky)' },
    3: { fileName: 'seminary.jpeg', desc: 'Eagel Update, Day 3:<br/>The Eagel loves watching people struggle with things he won\'t need to care about' },
    4: { fileName: 'cat.jpg', desc: 'Eagel Update, Day 4:<br/>My cat knows how to bow properly to the Eagel' },
    5: { fileName: 'bike.jpeg', desc: 'Eagel Update, Day 5:<br/>Ready to go on a road trip!' },
    6: { fileName: 'GG.jpeg', desc: 'Eagel Update, Day 6:<br/>Interesting what rules apply to humans... But I can\'t find anything about Eagels hehe' },
    7: { fileName: 'inside.jpeg', desc: 'Eagel Update, Day 7:<br/>Pretty dark here in the locker... Luckily there are cereal bars!' },
    8: { fileName: 'Waffle.jpeg', desc: 'Eagel Update, Day 8:<br/>Look at our spiky friend getting some waffles at the local supermarket.' },
    9: { fileName: 'music.jpeg', desc: 'Eagel Update, Day 9:<br/>Listening to good old Rolling Stones music with his new buddy!' },
    10: { fileName: 'floof.jpeg', desc: 'Eagel Update, Day 10:<br/>The Eagel discovered a new species in this house. It seems he now has taken the leadership of the floof-gang!' },
    11: { fileName: 'map.jpeg', desc: 'Eagel Update, Day 11:<br/>The Eagel found my new world map and decided to find a new vacation destination!' },
    12: { fileName: 'horror.jpeg', desc: 'Eagel Update, Day 12:<br/>The Eagel found a bunch of old horror tapes. I think he actually found his favorite one...' },
    13: { fileName: 'magic.jpeg', desc: 'Eagel Update, Day 13:<br/>The Eagel tried some magic today... Hopefully he\'s not going to burn anything...he\'s quite strong...' },
    14: { fileName: 'membership.jpeg', desc: 'Eagel Update, Day 14:<br/>Today the Eagel helped me with the membership cards and we\'re making good progress! Maybe at the end of the week we\'ll be able to order them' },
    15: { fileName: 'goddess.jpeg', desc: 'Eagel Update, Day 15:<br/>Today, the Eagel befriended a goddess from another universe and used his hair as a nest for her...<br/>Didn\'t know he could that but it\'s definitely awesome' },
    16: { fileName: 'timetravel.jpeg', desc: 'Eagel Update, Day 16=17:<br/>Some critics may say, "Hannes forgot to post yesterday", but those people weren\'t as privileged as I was yesterday.<br/>For the first time, I was able to watch the Eagel timetravel. Apparently yesterday and today is actually the same day!<br/>Isn\'t that awesome!!!' },
    17: { fileName: 'timetravel.jpeg', desc: 'Eagel Update, Day 17=16:<br/>Some critics may say, "Hannes forgot to post yesterday", but those people weren\'t as privileged as I was yesterday.<br/>For the first time, I was able to watch the Eagel timetravel. Apparently yesterday and today is actually the same day!<br/>Isn\'t that awesome!!!' },
    18: { fileName: 'party.jpeg', desc: 'Eagel Update, Day 18:<br/>The Eagel, left behind as we did not take a group picture with him...<br/>Coordination somewhat disappointing, <b>7</b> people forgot him, we need to repay him that!' },
    19: { fileName: 'schtrong.jpeg', desc: 'Eagel Update, Day 19:<br/>He just spent all dax collecting THE POWER.<br/><br/>now he is very schtrong' },
    20: { fileName: 'gardening.jpeg', desc: 'Eagel Update, Day 20:<br/>Eagel giving his best at gardening...<br/>The Lego cactus hasn\'t died yet after three hours!<br/>He\'s so incredible, it\'s pure mastery' },
    21: { fileName: 'light.jpeg', desc: 'Eagel Update, Day 21:<br/>The Eagel helped me today with putting up LED-Lights!<br/>His Mini-Gun glowed really nice but sadly the camera didn\'t capture that quite right.' },
    22: { fileName: 'cactus.jpeg', desc: 'Eagel Update, Day 22:<br/>The Eagel and his similarly circular friend - the cactus!' },
    23: { fileName: 'pasta.jpeg', desc: 'Eagel Update, Day 23:<br/>To make the Eagel feal a little bit more at home, I placed him next to the offspring of his mama, the Spaghetti-Monster.<br/><br/><br/>(P. S. NO THIS IS NOT AN AD FOR A CERTAIN PASTA COMPANY' },
    24: { fileName: 'quotes.jpeg', desc: 'Eagel Update, Day 24:<br/>Onehundredandtwelve citations. I think the pig\'s whistling. That took too long' },
    25: { fileName: 'art.jpeg', desc: 'Eagel Update, Day 25:<br/>The Eagel is appreciating the highest arts!<br/><br/>Cultureeeee' },
    26: { fileName: 'kilt.jpeg', desc: 'Eagel Update, Day 26:<br/>Soooooooooooo fashionable' },
    27: { fileName: 'promotion.jpeg', desc: 'Eagel Update, Day 27:<br/>The Eagel only promotes the most professional businesses!' },
    28: { fileName: 'plushies.jpeg', desc: 'Eagel Update, Day 28:<br/>The Eagel has made a lot of friends on his journey across the world...<br/>and now there are even more :D' },
    29: { fileName: 'billiard.jpeg', desc: 'Eagel Update, Day 29:<br/>I don\'t know if it is because he is a sphere himself, but he is way too good at billiards' },
    30: { fileName: 'darts.jpeg', desc: 'Eagel Update, Day 30:<br/>Today we tried darts and well...<br/>he had his own kind of strategies.<br/>Does each spike count individually or do I go by best hit? I have no idea<br/>But he definitely won, because I\'m too overwhelmed to continue.' },
    31: { fileName: 'sleepy.jpeg', desc: 'Eagel Update, Day 31:<br/>Today the Eagel went to bed early, because the last few days where very exhausting and he may or may not has stayed up too late yesterday.<br/>Sleepy time' },
    32: { fileName: 'electric.jpeg', desc: 'Eagel Update, Day 32:<br/>It is normal for the Eagel to emitting a strong electromagnetic field, if this is not the case please charge him as soon as possible<br/>The more you know' },
    33: { fileName: 'fishing.jpeg', desc: 'Eagel Update, Day 33:<br/>Give a man a fish and you feed him for one day;<br/>Teach the Eagel how to fish and...<br/>well we don\'t know what will happen...<br/>yet' },
    34: { fileName: 'dnd.jpeg', desc: 'Eagel Update, Day 34:<br/>Today the Eagel is diving into the great world of D&D.<br/>His dice trows are always perfect, like the Eagel himself.🎲' },
    35: { fileName: 'colors.jpeg', desc: 'Eagel Update, Day 35:<br/>The Eagel checked out his new thronelike carriage transportation system - but needed to have a serious conversation with me about the color scheme afterwards (Seriously? Pink AND orange AND turquoise?!?)' },
    36: { fileName: 'schoolbag.jpeg', desc: 'Eagel Update, Day 36:<br/>Today, the Eagel camouflaged as a 3rd-grader, as he wanted to get to know the low-level educational institution called primary school attended by one of the little tribe members he\'s currently visiting.' },
    37: { fileName: 'detective.jpeg', desc: 'Eagel Update, Day 37:<br/>Today, the Eagel discovered a new professional branch - detecting. Maybe the equipment can help to uncover the true criminal nature of the pesky birds, so he finally - and legally - can get rid of them!' },
    38: { fileName: 'racing.jpeg', desc: 'Eagel Update, Day 38:<br/>Tonight, the Eagel broke several speed records. Without reaching the foot pedals. Well, the Eagel works in mysterious ways.' },
    39: { fileName: 'aquarium.jpeg', desc: 'Eagel Update, Day 39:<br/>The Eagel wanted to research a new species,but unfortunately discovered his hydrophobia.' },
    40: { fileName: 'bunny.jpeg', desc: 'Eagel Update, Day 40:<br/>After the Eagel didn\'t feel appreciated enough by the local floof species (although sharing similar fur coloring)...' },
    41: { fileName: 'rewatching.jpeg', desc: 'Eagel Update, Day 41:<br/>...he decided to relive his magnificent flying experience to get himself out of his foul mood.' },
    42: { fileName: 'fridge.jpeg', desc: 'Eagel Update, Day 42:<br/>Sorry for the delay - after the Eagel involved himself with the contents of the fridge, he got a slight... indigestion.' },
    43: { fileName: 'books.jpeg', desc: 'Eagel Update, Day 43:<br/>There are no such things as too many books - only too little shelf. And the Eagel is just looking at the first row (there are two more behind).' },
    44: { fileName: 'microscope.jpeg', desc: 'Eagel Update, Day 44:<br/>Today the Eagel detected a whole new universe through his microscope.' },
    45: { fileName: 'dj.jpeg', desc: 'Eagel Update, Day 45:<br/>Newfound profession: Eagel is a DJ (musical reference intended)<br/>for further reference see: <a href="https://youtu.be/zXUrVJNIcgA">https://youtu.be/zXUrVJNIcgA</a>)' },
    46: { fileName: 'labyrinth.jpg', desc: 'Eagel Update, Day 46:<br/>The Eagel is winning. Always.' },
    47: { fileName: 'banana.jpg', desc: 'Eagel Update, Day 47:<br/>Found some strange looking earth worms. Tasted like bananas. Ate them all but two.' },
    48: { fileName: 'soccer.jpg', desc: 'Eagel Update, Day 48:<br/>The last dance: Klopp vs. Guardiola, and the world watches. And the Eagel too.' },
    49: { fileName: 'hiding.jpg', desc: 'Eagel Update, Day 49:<br/>Playing hide and seek' },
    50: { fileName: 'ball.jpg', desc: 'Eagel Update, Day 50:<br/>Falling in love. It has such a lovely shape!!!!' },
    51: { fileName: 'potato.jpg', desc: 'Eagel Update, Day 51:<br/>Since the Eagel had to spend his day locked inside a little dark room called locker, he needed a bit of positivity. How fortunate that he met the positive potato.' },
    52: { fileName: 'council.jpg', desc: 'Eagel Update, Day 52:<br/>Today the Eagel held an important conference with some of his hedgehog friends from earth. They had important business to talk about, but still found the time for a little snack, after all: an apple a day keeps the doctor away.' },
    53: { fileName: 'hug.jpg', desc: 'Eagel Update, Day 53:<br/>The Eagel found an interesting book, which he studied really hard, he even found himself some glasses (for the experience).<br/>Hopefully he was able to get the information he wanted.' },
    54: { fileName: 'lost lands.jpg', desc: 'Eagel Update, Day 54:<br/>Today the Eagel tried an adventure game from the Hidden-Object genre called: “Lost Lands (1) Dark Overlord”. I think he enjoyed it.' },
    55: { fileName: 'gemstones.jpg', desc: 'Eagel Update, Day 55:<br/>Today the Eagel took his time to look at some gemstones, fossils and minerals and tried to identify them.' },
    56: { fileName: 'hiding cat.jpg', desc: 'Eagel Update, Day 56:<br/>Today the Eagel played hide and seek with my cat and when he finally found her she was underneath my bed.', image: 'hiding cat 2.jpg' },
    57: { fileName: 'stamps.jpg', desc: 'Eagel Update, Day 57:<br/>After he had a ton of fun with the gemstones,… the Eagel decided he should try sorting coins and stamps next.' },
    58: { fileName: 'glowsticks.jpg', desc: 'Eagel Update, Day 58:<br/>Today the Eagel and his little friend found those funny glow in the dark sticks in a cupboard, so they decided that they wanted to try them.' },
    59: { fileName: 'karaoke.jpg', desc: 'Eagel Update, Day 59:<br/>After the Eagel watched YouTube Shorts and saw a video from a vocal coach he catched the karaoke fever.<br/>(For further references: <a href="https://youtube.com/shorts/VXY9vlvedD0?si=r7vWb7Ykot_mLZY0)">https://youtube.com/shorts/VXY9vlvedD0?si=r7vWb7Ykot_mLZY0)</a>' },
    60: { fileName: 'register.jpg', desc: 'Eagel Update, Day 60:<br/>Just Eagel trying to steal the K1 register to get a new haircut.' },
    61: { fileName: 'haircut.jpg', desc: 'Eagel Update, Day 61:<br/>What do you think about the new hairstyle?' },
    62: { fileName: 'mirror.jpeg', desc: 'Eagel Update, Day 62:<br/>Can you tell who is the real Eagel?' },
    63: { fileName: 'cool.jpeg', desc: 'Eagel Update, Day 63:<br/>They see me rollin\'<br/>they hatin\'' },
    64: { fileName: 'doggo.jpeg', desc: 'Eagel Update, Day 64:<br/>Doggo :)' },
    65: { fileName: 'birds.jpeg', desc: 'Eagel Update, Day 65:<br/>Know thy self, know thy enemy. -Sun Tzu' },
    66: { fileName: 'hog rider.jpeg', desc: 'Eagel Update, Day 66:<br/>Hooog Riiidaaa!!' },
    67: { fileName: 'dual sword.jpeg', desc: 'Eagel Update, Day 67:<br/>The Eagel has learned the art of dual wielding swords...' },
    68: { fileName: 'pistol.jpeg', desc: 'Eagel Update, Day 68:<br/>...guns are still better tho.' },
    69: { fileName: 'sus.jpeg', desc: 'Eagel Update, Day 68:<br/>Looking around the House, the Eagel found a Mogus. Unfortunately, the imposter already got it.' },
    70: { fileName: 'tiny.jpeg', desc: 'Eagel Update, Day 70:<br/>Look! The Eagel found another one of his little cousins!' },
    71: { fileName: 'clock.jpeg', desc: 'Eagel Update, Day 71:<br/>Oh no! The Eagel forgot the time! Well, seems like there will be two DDoEs today!' },
    72: { fileName: 'painting.jpeg', desc: 'Eagel Update, Day 72:<br/>The Eagel found this painting of a magical knight. What could his name be??' },
    73: { fileName: 'murder mystery.jpeg', desc: 'Eagel Update, Day 73:<br/>Time for a round of good old Hypixel murder mystery.' },
    74: { fileName: 'hamster.jpeg', desc: 'Eagel Update, Day 74:<br/>The Eagel has found a new specimen of floof - or has it found him?' },
    75: { fileName: 'school.jpeg', desc: 'Eagel Update, Day 75:<br/>Time to prepare for school again...' },
    76: { fileName: 'wikihow.png', desc: 'Eagel Update, Day 76:<br/>I\'m sorry for the ping, but this is a serious topic: I\'ve heard some of you are forgetting to read the Daily Doses of Eagel, which is totally unacceptable. To prevent that from happening, follow the official Eagel guide to turn on your notifications, and you\'ll never miss an update again!', image: 'wikihow2.png' },
    77: { fileName: 'concert.jpeg', desc: 'Eagel Update, Day 77:<br/>Today the Eagel wanted to hear some componists from the romantic era.' },
    78: { fileName: 'helmet.jpeg', desc: 'Eagel Update, Day 78:<br/>Now the Eagel is ready for the next bike tour - do you think the helmet fits?' },
    79: { fileName: 'winnetou.jpeg', desc: 'Eagel Update, Day 79:<br/>Im really tired, because I had to read out Winnetou to the Eagel - he wanted to hear all three books.' },
    80: { fileName: 'mexican.jpeg', desc: 'Eagel Update, Day 80:<br/>Right now the Eagel is on a visit in Mexico! But there is the time shift so we got it 8 hours later...' },
    81: { fileName: 'minigolf.jpeg', desc: 'Eagel Update, Day 81:<br/>The Eagel tries to relax this Sunday so he played Minigolf.' },
    82: { fileName: 'cherries.jpeg', desc: 'Eagel Update, Day 82:<br/>After work, the Eagel strolled through the Four-Worlds-Garden in Minecraft.' },
    83: { fileName: 'plane.jpeg', desc: 'Eagel Update, Day 83:<br/>The Eagel thought back to his time with _, so he built a little plane.' },
    84: { fileName: 'gnat.jpeg', desc: 'Eagel Update, Day 84:<br/>The Eagel has found an oversized gnat on the dusty shelf! Will they join forces with the birds?' },
    85: { fileName: 'upside down headphones.jpeg', desc: 'Eagel Update, Day 85:<br/>Chilling and hearing music! But I think he\'s wearing the headphones wrong...' },
    86: { fileName: 'drums.jpeg', desc: 'Eagel Update, Day 86:<br/>The Eagel is playing a spiky beat - Ba Dum tss' },
    87: { fileName: 'heuteshow.jpeg', desc: 'Eagel Update, Day 87:<br/>The Eagel is watching the Heute Show - Mr. Söder loves Pandas...' },
    88: { fileName: 'schnapps.jpeg', desc: 'Eagel Update, Day 88:<br/>Because of the number of the Day (88), the Eagel drank schnapps: Now he\'s feeling bad...' },
    89: { fileName: 'learningSP2.jpeg', desc: 'Eagel Update, Day 89:<br/>Im sorry but the Eagel had to help me to learn for the Sports Abitur today so we didn\'t post something...' },
    90: { fileName: 'tree.jpeg', desc: 'Eagel Update, Day 90:<br/>Today the Eagel enjoyed the green garden - can you find him?', image: 'garden.jpeg' },
    91: { fileName: 'blahaj.jpeg', desc: 'Eagel Update, Day 91:<br/>Today the Eagel spent some time trying to figure out how to get rid of birds entirely. He found help from a very experienced war general...' },
    92: { fileName: 'sonnet.jpeg', desc: 'Eagel Update, Day 92:<br/>After having found this awful bottle the Eagel decided to continue building his masterplan against birds. So he made his way to the library and got slightly distracted. However this distraction has inspired him to write a beautiful shakespearean sonett:<br/><br/>A bird, a beast of looks vilely trech\'rous<br/>A kind only w\'rth to f\'rociously judgeth<br/>And of charact\'r trully trech\'rous<br/>A kind, i wholeheartedly grudgeth<br/><br/>I once hath lived \'mongst thy kind<br/>Bethought we w\'re flying in a friendy<br/>Though then thee cutteth those from behind<br/>Making me falleth to taketh with thy envy<br/><br/>Whilst i returneth to mine own gl\'ry<br/>And am did value liketh i am of kings<br/>Mine own mem\'ry shalt keepeth mine own st\'ry<br/>I shalt not f\'rget the way thee did steal mine own wings<br/><br/>And as thee didst to me at which hour i ment well<br/>I shall maketh thee woe deep\'r than i hath fell' },
    93: { fileName: 'burning.jpeg', desc: 'Eagel Update, Day 93:<br/>This time the Eagel got more radical: Instead of writing about burning birds he actually burned a considerable amount of them. Who would\'ve thought that birds burn that well?' },
    94: { fileName: 'pullup.jpeg', desc: 'Eagel Update, Day 94:<br/>He has mastered war, he has mastered fire, he has mastered language but what is missing? After watching the two pupils at home he realized: He needs strength. So he studied their movements and mastered the art of gymnastics today. And once he got bored he easily broke the human world record for the most pull-ups. It is truly  magnificent what the Eagel can do....' },
    95: { fileName: 'drugs.jpeg', desc: 'Eagel Update, Day 95:<br/>After a very exhausting week the Eagel decided to try out the human way of relaxing: drugs. He wasn\'t a fan. Don\'t do drugs, kids or the Eagel will haunt you' },
    96: { fileName: 'letter bottle.jpeg', desc: 'Eagel Update, Day 96:<br/>The Eagel tried to relax this week, he really did. But pesky birds never rest so the Eagel can\'t either. Today General Blahaj send a message to the Eagel\'s beach resort. The fish seem to have caught wind to where the central layer of the birds is located. He will have to cut this vacation short to investigate...' },
    97: { fileName: 'investigation.jpeg', desc: 'Eagel Update, Day 97:<br/>After the hints of yesterday the Eagel started his investigation and found out some very interesting things. He is incredibly close to cracking the case...' },
    98: { fileName: 'graz.jpeg', desc: 'Eagel Update, Day 98:<br/>After this very exhausting week of searching the Eagel finally found the bird base. So he and his war general took matters into their own hand and did what had to be done...' },
    99: { fileName: 'beep.png', desc: 'Eagel Update, Day 99:<br/>The Eagel was very angry after she forgot to get him today. Let us be charitable and pretend she was so grief-struck about the destruction of Graz instead of just forgetful' },
    100: { fileName: 'debating.png', desc: 'Eagel Update, Day 100' },
    101: { fileName: 'bowl.jpeg', desc: 'Eagel Update, Day 101:<br/>After the shock of being forcefully removed from the debate, the Eagel longed for his old followership, whom he hasn\'t seen for a while due to the Abi. He remained glued to the mobile all through the day with an empty salad bowl giving him a feeling of security in this wild world.' },
    102: { fileName: 'books2.jpeg', desc: 'Eagel Update, Day 102:<br/>On Sunday the Eagel took towards some traditional bookshelf-climbing, which miraculously took him towards the English history books on her shelves. She and the Eagel couldn\'t agree more in their liking of hiking and English history books.' },
    103: { fileName: 'pumpkin oil.jpeg', desc: 'Eagel Update, Day 103:<br/>The Eagel got to know Styrian pumpkin oil and realized that attacking Graz isn\'t such a good idea after all because of the extra power you gain from it.' },
    104: { fileName: 'pushups.jpeg', desc: 'Eagel Update, Day 104:<br/>Having gained new strength the Eagel used my yoga mat for some push-ups. Not easy with certain anatomical challenges…' },
    105: { fileName: 'pushupsAustria.png', desc: 'Eagel Update, Day 105:<br/>United in challenges, the Eagel and I practiced together.' },
    106: { fileName: 'sani.jpeg', desc: 'Eagel Update, Day 106:<br/>After a taxing day at school, which included sitting for the Sani-Prüfung without the announcement of results yet, the students eagerly anticipate the outcome. Nevertheless, the school community takes a moment to express appreciation for the presence and support of the Eagel, a symbol of strength and guidance, throughout the day.' },
    107: { fileName: 'belt.jpeg', desc: 'Eagel Update, Day 107:<br/>It seems it\'s time for more training, there\'s still much I can learn from the Eagel, who seems to excel at everything. Even though he appears to be a beginner with a white belt, don\'t let that deceive you. It seems like it\'s just a disguise hiding his true skill. It feels like I stand no chance against such mastery!' },
    108: { fileName: 'cat1.jpeg', desc: 'Eagel Update, Day 108:<br/>There\'s nothing more relaxing than gazing out the window with a new friend. After meeting them all, he decided to spend time with each one individually, getting to know them better day by day.' },
    109: { fileName: 'cat2.jpeg', desc: 'Eagel Update, Day 109:<br/>It\'s definitely a wonderful spot to hang out. This time, Marcel joined the Eagel, and they\'re thoroughly enjoying their time together. What beautiful weather we\'re having, despite the heavy rain we experienced just moments ago!' },
    110: { fileName: 'cat3.jpeg', desc: 'Eagel Update, Day 110:<br/>Next in line is Charlie, who appears rather astonished? What could he have discovered?<br/>(Seems like everyone wants to be by the window)' },
    111: { fileName: 'cat4.jpeg', desc: 'Eagel Update, Day 111:<br/>Lastly, we have Hannah, always sleeping in my chair. Having met a couple of new friends, they all seem to have taken a liking to the Eagel. Meanwhile, he has claimed a spot of his own too.' },
    112: { fileName: 'cat5.jpeg', desc: 'Eagel Update, Day 112:<br/>Lying far apart, they seem to need some space. The Eagel just wants to hang out with them, at least a bit more.' },
    113: { fileName: 'trunk.jpeg', desc: 'Eagel Update, Day 113:<br/>Somehow, even though the Eagel has experienced some truly great things, something is missing. Today the Eagel decided to pack his bag and go on a journey of self discovery. And what better way to do this than with a change of scenery?' },
    114: { fileName: 'beagel1.jpeg', desc: 'Eagel Update, Day 114:<br/>Every good self discovery starts with thinking about your past. Due to the Eagels complicated history, he started writing it down to keep track...' },
    115: { fileName: 'weed.jpeg', desc: 'Eagel Update, Day 115:<br/>The Eagel is living the high life on this self discovery journey' },
    116: { fileName: 'beagel2.jpeg', desc: 'Eagel Update, Day 116:<br/>The Eagel has started to gather his thoughts and memories in a little side project of his' },
    117: { fileName: 'bedsheets.jpeg', desc: 'Eagel Update, Day 117:<br/>After a hard day of working on his project the Eagel laid down and watched some TV shows to relax' },
    118: { fileName: 'workshop1.jpeg', desc: 'Eagel Update, Day 118:<br/>The Eagel locked himself into the workshop working countless hours on something. I wonder what exactly he is planning to do?' },
119: { fileName: 'workshop2.jpeg', desc: 'Eagel Update, Day 119:<br/>It is quite frustrating when the Eagel doesn\'t tell you what he\'s doing' },
    120: { fileName: 'outfit.jpeg', desc: 'Eagel Update, Day 120:<br/>Self discovery can be fun- so today the Eagel is going out to partyyyy' },
    121: { fileName: 'gardening2.jpeg', desc: 'Eagel Update, Day 121:<br/>The Eagel partied so hard that he had to miss out on yesterdays post to catch up on sleep. So today he just spent a relaxing day with gardening' },
    122: { fileName: 'accordion.jpeg', desc: 'Eagel Update, Day 122:<br/>Today the Eagel delighted this household with his musical gift. Our ears feel blessed to have been able to hear his talent' },
    123: { fileName: 'maths.jpeg', desc: 'Eagel Update, Day 123:<br/>Math is a conspiracy made up by birds to torture the Eagel\'s creation', image: '123img.jpeg' },
    124: { fileName: 'chicken.jpeg', desc: 'Eagel Update, Day 124:<br/>Why wasn\'t there a post yesterday? It is not due to my incompetence, the Eagel got into a fight with a chicken and spent yesterday in the ER...' },
    125: { fileName: 'recover.jpeg', desc: 'Eagel Update, Day 125:<br/>That\'s why today he was ordered to stay in bed and recover' },
    126: { fileName: 'wutz.jpeg', desc: 'Eagel Update, Day 126:<br/>Yes 👍 (No idea how to describe this picture)' },
    127: { fileName: 'reading.jpeg', desc: 'Eagel Update, Day 127:<br/>Reading his newest acquisition 👍' },
    128: { fileName: 'theater.jpeg', desc: 'Eagel Update, Day 128:<br/>The mighty Eagel on Stage!' },
    129: { fileName: 'drums2.jpeg', desc: 'Eagel Update, Day 129:<br/>Drumming...I don\'t know if he\'s doing it right, but he looks like he\'s having fun 👍' },
    130: { fileName: 'election.jpeg', desc: 'Eagel Update, Day 130:<br/>The Eagel is doing his part for democracy ✨<br/>As voting is a serious process, he\'s studying all the party goals and is discussing them with his smol friend to make the best choice possible, like any responsible hedgehog should 👍', image: '130img.jpeg' },
    131: { fileName: 'abi.jpeg', desc: 'Eagel Update, Day 131:<br/>In eternal service of the Eagel.' },
    132: { fileName: 'plane_building.jpeg', desc: 'Eagel Update, Day 132:<br/>Oh god, he has started work on some mystery project again... Rumours say he heard that his smol companion is trying to take over the skies and already completed first test runs, is this an attempt of catching up? Will this be a race for air superiority within Eagelkind?' },
    133: { fileName: 'spiky_game.jpeg', desc: 'Eagel Update, Day 133:<br/>Enjoying a spiky game with spiky friends<br/><br/><br/>(I apologize for the very, let\'s say... inconsistent rate of uploads, but on some days I just can\'t find the Eagel, seems like he\'s on some secret missions all the time... 😇)' },
    134: { fileName: 'landtag.jpeg', desc: 'Eagel Update, Day 134:<br/>I wonder why he is here...' },
    135: { fileName: 'certificate.jpeg', desc: 'Eagel Update, Day 135:<br/>After the Eagel has been to the Landtag, he\'s now gaining some laboratory experience in order to find out more about the human species, a rather strange form of life. I wonder what he\'s planning to do with his new knowledge about genetic fingerprinting...' },
    136: { fileName: 'risiko1.jpeg', desc: 'Eagel Update, Day 136:<br/>I got lucky that I was able to take this picture, once the Eagel realized I was there, he was eager to change the subject...', image:'136img.jpeg' },
    137: { fileName: 'pride.jpeg', desc: 'Eagel Update, Day 137:<br/>HAPPY PRIDE Y\'ALL!!!<br/>It\'s a bit late, but happy pride month! The Eagel obviously supports basic human right and marriage equality (congrats to Thailand, where the bill was finally passed).<br/>SLAYYY' },
    138: { fileName: 'theater2.jpeg', desc: 'Eagel Update, Day 138:<br/>While celebrating Pride Month, the Eagel has been invited as a special guest to theater class, blowing our minds away and creeping out _' },
    139: { fileName: 'fruits.jpeg', desc: 'Eagel Update, Day 139:<br/>Today the Eagel has been having a little feast to prepare himself for the next step of his plan...' },
    140: { fileName: 'risiko2.jpeg', desc: 'Eagel Update, Day 140:<br/>Today\'s the day, Iceland was just the beginning, now the whole world will know about the magnificence of the Eagel!!' },
    141: { fileName: 'hackerman.jpeg', desc: 'Eagel Update, Day 141:<br/>Hackerman B)' },
    142: { fileName: 'trafalgar.jpeg', desc: 'Eagel Update, Day 142:<br/>After conquering both the continents and the internet, the Eagel now has the world at his feet' },
    143: { fileName: 'other_than_me.jpeg', desc: 'Eagel Update, Day 143' },
    144: { fileName: 'electronics.jpeg', desc: 'Eagel Update, Day 144:<br/>⚡Bzz⚡<br/>Oh, nothing to see here' },
    145: { fileName: 'mayor.jpeg', desc: 'Eagel Update, Day 145:<br/>For his magnificent achievement (or as haters call it: world domination) the Eagel got an award from the mayor' },
    146: { fileName: 'monkey.jpeg', desc: 'Eagel Update, Day 146:<br/>New alliances are being forged in Freiburg' },
    147: { fileName: 'climbing.jpeg', desc: 'Eagel Update, Day 147:<br/>On top of the world' },
    148: { fileName: 'natural_history.jpeg', desc: 'Eagel Update, Day 148:<br/>After visiting the natural history museum in Karlsruhe, we have some undeniable proof of ancient portrayals of the Eagel. [The water animals are "Seeigel" and "Igelfische"]', image: "148img.jpeg" },
    149: { fileName: 'dresses.jpeg', desc: 'Eagel Update, Day 149:<br/>The Eagel visited a collection of the wedding dresses of all maids and gentlemen, who could only wish to wed him. Poor maids (and Gentlemen). They had no idea, they would never be worthy candidates for being the spouse of the holy, one and only Eagel.' },
    150: { fileName: 'theater3.jpeg', desc: 'Eagel Update, Day 150:<br/>The Eagel went to watch a Theater Performance, which told the story of a glorious mighty hero on his journey of glory and revenge. Rumors say it might be inspired by a true story. Of course the Eagel rented the entire audience for himself only. He doesn\'t need to share his entertainment with peasants.' },
}

// n: { fileName: '.jpeg', desc: 'Eagel Update, Day n:<br/>', image: '' },